// Auto-generated by tube_lut_gen.py
// Tube: 12AX7
// Do not edit manually

// LUT dimensions
parameter LUT_SIZE    = 256;
parameter LUT_BITS    = 8;  // 8 bits to address 256 entries

// Physical ranges (scaled to fixed point for address calculation)
// Vpk: 0.0V to 300.0V
// Vgk: -4.0V to 0.0V
parameter VPK_MIN_MV  = 0;   // millivolts
parameter VPK_MAX_MV  = 300000;
parameter VGK_MIN_MV  = -4000;
parameter VGK_MAX_MV  = 0;

// Scale factors (multiply float by these to get LUT integer values)
parameter IP_SCALE    = 10000;   // Ip * 10000 = 16-bit int
parameter DIP_SCALE   = 100000;  // dIp/dVgk * 100000 = 16-bit int
parameter DIP_VPK_SCALE = 100000;  // dIp/dVpk * 100000 = 16-bit int

// Tube constants (for reference / soft parameter override)
parameter real MU  = 92.08;
parameter real EX  = 1.29;
parameter real KG1 = 1304.71;
parameter real KP  = 561.08;
parameter real KVB = 15101.91;
