// Auto-generated by gen_1d_luts.py -- 1D LUT parameters for koren_direct.v
// Do not edit manually

// 1D LUT dimensions
localparam KLUT_SIZE = 64;
localparam KLUT_BITS = 6;  // 6 bits to address 64 entries

// 12AX7 Koren constants in Q16.16
localparam signed [31:0] KOREN_MU_FP     = 32'sd6034555;    // 92.08
localparam signed [31:0] KOREN_KP_FP     = 32'sd36770939;    // 561.08
localparam signed [31:0] KOREN_KG1_FP    = 32'sd85505475;   // 1304.71
localparam signed [31:0] KOREN_INV_MU_FP = 32'sd712; // 1/92.08
localparam signed [31:0] KOREN_INV_KP_FP = 32'sd117; // 1/561.08

// Sqrt LUT: index = (Vpk - VPK_MIN) / VPK_STEP
localparam signed [31:0] SQRT_VPK_MIN_FP  = 32'sd0;
localparam signed [31:0] SQRT_VPK_STEP_FP = 32'sd312076;

// Softplus LUT: index = (inner - SOFTPLUS_MIN) / SOFTPLUS_STEP
localparam signed [31:0] SOFTPLUS_MIN_FP  = 32'sd-393216;
localparam signed [31:0] SOFTPLUS_MAX_FP  = 32'sd393216;
localparam signed [31:0] SOFTPLUS_STEP_FP = 32'sd12483;

// Power LUT: index = (Ed - ED_MIN) / ED_STEP
localparam signed [31:0] POWER_ED_MIN_FP  = 32'sd0;
localparam signed [31:0] POWER_ED_MAX_FP  = 32'sd39322;
localparam signed [31:0] POWER_ED_STEP_FP = 32'sd624;
