// Auto-generated by tube_lut_gen.py
// Preamp: 12AX7, Power amp: 6L6
// LUT size: 128x128 (both tubes)
// Do not edit manually

// LUT dimensions
parameter LUT_SIZE    = 128;
parameter LUT_BITS    = 7;  // 7 bits to address 128 entries

// 12AX7 preamp ranges
parameter VPK_MIN_MV  = 0;   // millivolts
parameter VPK_MAX_MV  = 300000;
parameter VGK_MIN_MV  = -4000;
parameter VGK_MAX_MV  = 0;

// 6L6 power amp ranges
parameter VPK_MIN_MV_6L6  = 0;
parameter VPK_MAX_MV_6L6  = 500000;
parameter VGK_MIN_MV_6L6  = -50000;
parameter VGK_MAX_MV_6L6  = 0;

// Scale factors (multiply float by these to get LUT integer values)
parameter IP_SCALE    = 10000;   // Ip * 10000 = 16-bit int
parameter DIP_SCALE   = 100000;  // dIp/dVgk * 100000 = 16-bit int
parameter DIP_VPK_SCALE = 10000000;  // dIp/dVpk * 10000000 = 16-bit int

// 12AX7 tube constants (for reference)
parameter real MU_12AX7  = 100.0;
parameter real EX_12AX7  = 1.4;
parameter real KG1_12AX7 = 1060.0;
parameter real KP_12AX7  = 600.0;
parameter real KVB_12AX7 = 300.0;

// 6L6 tube constants (for reference)
parameter real MU_6L6  = 10.11;
parameter real EX_6L6  = 1.37;
parameter real KG1_6L6 = 406.6;
parameter real KP_6L6  = 31.2;
parameter real KVB_6L6 = 640.7;
